Django Site/hang/urls.py
from django.conf.urls import url
from . import views

app_name = 'hang'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^game/$',views.game,name = 'game'),
    url(r'^hint/$',views.hint,name = 'hint'),
    url(r'^add/$',views.add,name = 'add'),
]

Django Site/hangman/urls.py
from django.conf.urls import include,url
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hang/',include('hang.urls')),
]

Django Site/hang/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Words(models.Model):
    alpha = models.CharField(max_length=500)

    def __str__(self):
        return self.alpha

Django Site/hang/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
import random
# Create your views here.
global word,blanks,origuess,wrongGuess
global vowels,selectedChar,noOfHints
def index(request):
    global word,blanks,origuess,wrongGuess
    global vowels,selectedChar,noOfHints
    all_words = Words.objects.all()
    ind = random.randint(1,Words.objects.count())
    word = Words.objects.get(pk=ind).alpha
    vowels = ['a','e','i','o','u']  #used for hints
    selectedChar = []               #used for hints
    guess = ''
    blanks = 0
    wrongGuess = 1
    noOfHints = 3
    for char in word:
        asc = ord(char)
        if (ord('A')<=asc and ord('Z')>=asc) or (ord('a')<=asc and ord('z')>=asc):
            guess += '_'
            blanks+=1
        else:
            guess += char
    origuess = guess
    context = {'guess':guess,'wrongGuess':str(wrongGuess),'answer':word,'hint':"",'noOfHints':int(noOfHints)}
    return render(request,'hang/index.html',context)


def game(request):
    global word,blanks,origuess,wrongGuess
    global selectedChar,noOfHints
    guess = origuess
    character = request.POST['guessed']
    flag = 0
    # if len(guess)!=len(word):
    #     return HttpResponse(guess)
    if character=='':
        wrongGuess+=1
        context = {'guess':guess,'wrongGuess':str(wrongGuess),'answer':word,'hint':"",'noOfHints':int(noOfHints)}
        return render(request,'hang/index.html',context)
    character = character[:1]
    selectedChar.append(character.lower())
    if blanks:
        asc = ord(character)
        if (ord('A')<=asc and ord('Z')>=asc) or (ord('a')<=asc and ord('z')>=asc):
            for i in xrange(0,len(word)):
                if (character.upper() == word[i] or character.lower() == word[i]) and guess[i]=='_':
                    guess = guess[:i] + word[i] + guess[i+1:]
                    blanks-=1
                    flag=1
        if flag==0:
            wrongGuess+=1
        if blanks:
            origuess = guess
            context = {'guess':guess,'wrongGuess':str(wrongGuess),'answer':word,'hint':"",'noOfHints':int(noOfHints)}
            return render(request,'hang/index.html',context)
    return HttpResponse(wrongGuess)

def hint(request):
    global word
    global selectedChar,vowels,noOfHints
    flag = 0
    hint = ''
    if(noOfHints>0):
        noOfHints-=1
        if vowels!=[]:
            ch=random.choice(vowels)
            while vowels!=[] and ch in selectedChar:
                vowels.remove(ch)
                if vowels!=[]:
                    ch = random.choice(vowels)
            if(vowels!=[]):
                if ch in word:
                    hint = "Word contains '"+ch+"'..."
                else:
                    hint = "Word does not contains '"+ch+"'..."
                vowels.remove(ch)
                flag = 1
        if flag==0:
            consonents = ['b','c','d','f','g','h','j','k','l','m','n','p','q','r','s','t','v','w','x','y','z']
            temp = list(''.join([l for l in word.strip() if l in consonents]))
            ch=random.choice(temp)
            while temp!=[] and ch in selectedChar:
                temp.remove(ch)
                if temp!=[]:
                    ch = random.choice(temp)
            hint = "Word contains '"+ch+"'..."
    context = {'guess':origuess,'wrongGuess':str(wrongGuess),'answer':word,'hint':hint,'noOfHints':int(noOfHints)}
    return render(request,'hang/index.html',context)



def add(request):
    fp = open('hang/tvshows.txt','r')
    lines = fp.readlines()
    #commented as they should not get added again
    # for line in lines:
    #     a = Words()
    #     a.alpha = line[:-1]
    #     a.save()
    return HttpResponse("Done!!!")

Django Site/hang/templates/hang/index.html
<head>
    <title>{% block title %}Hangman{% endblock%}</title>
    <!--Loads the path to my static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'hang/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<div>
    {% for char in guess %}
        {{char}}
    {% endfor %}
</div>
<form class="navbar-form navbar-left" method="post" action="{% url 'hang:game' %}">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" class="form-control" name="guessed" value="">
        <input type="hidden" name="wrongGuess" value={{wrongGuess}}>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
    <div>
        {% with imageurl="hang/images/hang_"|add:wrongGuess|add:"n.gif" %}
            <img src="{% static imageurl %}" alt="Hangman Image"/>
        {% endwith %}
        {% if wrongGuess == "7" %}
            <br>Sorry, you have been hanged!!!<br>
            The Answer was {{answer}}
        {% endif %}
    </div>
</form>
<div>
    <form class="navbar-form navbar-left" method="post" action="{% url 'hang:hint' %}">
        {% csrf_token %}
        {% if wrongGuess == '4' or wrongGuess == '5' or wrongGuess == '6' %}
            {% if noOfHints != 0 %}
                <button type="submit" class="btn btn-warning" name="hinter">Hint</button>
            {% endif %}
        {%endif%}
    </form>
    {{hint}}
</div>
<div class="nav navbar-nav navbar-right">
    <img src="{% static "hang/images/animhangman.gif" %}" alt="Hangman Image"/>
</div>